import streamlit as st
from modules.navigation import SidebarNav

def intro():
    st.title("Content Detector")

    st.markdown(""" Content detectors are AI tools designed to analyze text and determine whether it was generated by a human or an AI model.
                These tools use various algorithms and techniques to evaluate the characteristics of the text, such as syntax, semantics, and patterns that may indicate AI generation.
                """)
    
    st.markdown("Content at scale: https://contentatscale.ai/about/?fpr=register")


def main():
    SidebarNav()
    intro()


if __name__ == "__main__":
    main()